import {
  generateShipArtifacts,
  type ShipGeneratorInput,
} from "@/lib/server/ship-generator";
import {
  failShipJob,
  getShipJobContext,
  getWorkspaceGitHubToken,
  updateProjectRepository,
  updateShipJob,
} from "@/lib/server/workspace-db";
import {
  createOrReuseDraftPullRequest,
  createRepositoryForUser,
  ensureBranchFromBase,
  getRepositoryDefaultBranch,
  parseGitHubRepository,
  upsertRepositoryTextFile,
} from "@/lib/server/github-client";

const delay = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

function slugify(input: string): string {
  const safe = input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return safe || "prototype";
}

export function startShipJobProcessing(workspaceId: string, jobId: string) {
  void processShipJob(workspaceId, jobId);
}

async function processShipJob(workspaceId: string, jobId: string) {
  try {
    const context = await getShipJobContext(workspaceId, jobId);
    if (!context) {
      await failShipJob(workspaceId, jobId, "Ship job context was not found");
      return;
    }
    const { project, job } = context;
    let repoRef = parseGitHubRepository(project.repository ?? "");
    const githubToken = await getWorkspaceGitHubToken(workspaceId);
    if (!githubToken) {
      await failShipJob(
        workspaceId,
        jobId,
        "GitHub is not connected for this workspace. Connect via GitHub Sync first."
      );
      return;
    }

    if (!repoRef) {
      await updateShipJob(workspaceId, jobId, "planning", {
        message: "Creating GitHub repository for this project...",
      });
      const baseRepoName = `sketch2ship-${slugify(project.name)}`;
      const description =
        project.ideaSummary?.trim() ||
        `MVP prototype for ${project.name} generated by Sketch2Ship.`;
      let created: { owner: string; repo: string } | null = null;
      for (const name of [
        baseRepoName,
        `${baseRepoName}-${project.id.slice(0, 8)}`,
      ]) {
        try {
          created = await createRepositoryForUser(name, description, githubToken);
          break;
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          if (
            msg.includes("name already exists") ||
            msg.includes("422") ||
            msg.includes("Repository creation failed")
          ) {
            continue;
          }
          throw err;
        }
      }
      if (!created) {
        await failShipJob(
          workspaceId,
          jobId,
          `Could not create repository: ${baseRepoName} (and fallback) already exist.`
        );
        return;
      }
      repoRef = created;
      const updated = await updateProjectRepository(
        workspaceId,
        project.id,
        `${repoRef.owner}/${repoRef.repo}`
      );
      if (updated) {
        Object.assign(project, updated.project);
      }
    }

    const branchName = `ship/${slugify(project.name)}-${job.id.slice(0, 6)}`;
    const selectedIssues = job.issueIds.length
      ? project.generatedIssues.filter((issue) => job.issueIds.includes(issue.id))
      : project.generatedIssues.slice(0, 4);
    const issueCount = selectedIssues.length;
    const selectedTaskTitles = selectedIssues.map((issue) => issue.title);
    const baseBranch = await getRepositoryDefaultBranch(repoRef, githubToken);
    const projectSummary =
      project.ideaSummary?.trim() ||
      `MVP prototype for ${project.name} generated from live spec and ship plan.`;

    await updateShipJob(workspaceId, jobId, "planning", {
      message: `Compiled an implementation brief from ${project.specSections.length} spec sections and ${project.milestones.length} milestones.`,
    });
    await delay(320);

    await updateShipJob(workspaceId, jobId, "scaffolding", {
      branchName,
      message: `Preparing ${repoRef.owner}/${repoRef.repo} on branch ${branchName} and mapping ${issueCount} issue(s) into tasks.`,
    });
    await ensureBranchFromBase(repoRef, baseBranch, branchName, githubToken);

    await updateShipJob(workspaceId, jobId, "implementing", {
      message: "Generating implementation with Gemini...",
    });
    const generatorInput: ShipGeneratorInput = {
      projectName: project.name,
      ideaSummary: projectSummary,
      specSections: project.specSections,
      milestones: project.milestones,
      selectedIssues,
    };
    const artifacts = await generateShipArtifacts(generatorInput);

    await upsertRepositoryTextFile(
      repoRef,
      branchName,
      "sketch2ship/SHIP_BRIEF.md",
      artifacts.shipBrief,
      "chore(sketch2ship): add ship brief",
      githubToken
    );

    for (const file of artifacts.files) {
      await upsertRepositoryTextFile(
        repoRef,
        branchName,
        file.path,
        file.content,
        `feat(sketch2ship): add ${file.path.split("/").pop()}`,
        githubToken
      );
    }

    await updateShipJob(workspaceId, jobId, "testing", {
      message:
        "Prototype files committed. Use CI checks in the pull request to validate build and tests.",
    });
    await delay(260);

    const pr = await createOrReuseDraftPullRequest(
      repoRef,
      branchName,
      baseBranch,
      `Ship prototype: ${project.name}`,
      [
        "## What this PR contains",
        `- Generated ship brief for **${project.name}**`,
        `- ${artifacts.files.length} implementation file(s) under \`sketch2ship/prototype/\``,
        "",
        "## Source of truth",
        "- Live spec requirements",
        "- Weekend ship milestones",
        issueCount
          ? `- Selected issues: ${selectedTaskTitles.slice(0, 6).join(", ")}`
          : "- Selected issues: none (defaulted to core scaffold)",
        "",
        "_Generated by Sketch2Ship AI Agent._",
      ].join("\n"),
      githubToken
    );
    await updateShipJob(workspaceId, jobId, "publishing", {
      pullRequestUrl: pr.url,
      message: `Opened draft PR #${pr.number} with generated implementation artifacts.`,
    });
    await delay(260);

    const entryHtml =
      artifacts.files.find((f) => f.path.endsWith(".html"))?.path ??
      "sketch2ship/prototype/index.html";
    const prototypeUrl = `https://github.com/${repoRef.owner}/${repoRef.repo}/blob/${branchName}/${entryHtml}`;
    const summary = `A working MVP shell for ${project.name} is now available with the primary flow implemented and deployment wired.`;
    await updateShipJob(workspaceId, jobId, "ready", {
      prototypeUrl,
      summary,
      pullRequestUrl: pr.url,
      message: "Prototype is live. Review the preview, then approve or request revisions.",
    });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Unexpected ship processing error";
    await failShipJob(workspaceId, jobId, message);
  }
}
