import { GoogleGenAI } from "@google/genai";
import type { GeneratedIssue, Milestone, SpecSection } from "@/lib/mock-data";

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface ShipArtifacts {
  shipBrief: string;
  files: GeneratedFile[];
}

export interface ShipGeneratorInput {
  projectName: string;
  ideaSummary: string;
  specSections: SpecSection[];
  milestones: Milestone[];
  selectedIssues: GeneratedIssue[];
}

const SHIP_PROMPT = `You are a ship engineer. Given a project spec and selected tasks, produce a ship brief (for developers) and multiple implementation files that realize the spec and execution plan.

Output a single JSON object with this exact structure (no markdown, no code fences):
{
  "shipBrief": "markdown string - developer-facing implementation brief with execution plan, acceptance criteria, scope snapshot derived from the spec",
  "files": [
    { "path": "sketch2ship/prototype/index.html", "content": "full file content" },
    { "path": "sketch2ship/prototype/styles.css", "content": "full file content" },
    { "path": "sketch2ship/prototype/app.js", "content": "full file content" },
    { "path": "sketch2ship/prototype/README.md", "content": "setup and usage instructions" }
  ]
}

Constraints:
- Generate files that implement the spec and selected tasks. Use multiple files: separate HTML, CSS, JS, and README. Add more files as needed (e.g. components, utils, config).
- All paths must be under sketch2ship/prototype/ (e.g. sketch2ship/prototype/index.html, sketch2ship/prototype/styles.css).
- index.html is the entry point; it may link to external CSS/JS. No external CDNs or npm—keep it runnable by opening index.html in a browser.
- shipBrief should reference spec sections and milestones.
- Each file's content must be a complete, valid file. Escape quotes and newlines for valid JSON.
- Implement the primary user flows from the spec. Focus on working MVP, not placeholder content.`;

function buildFallbackShipArtifacts(input: ShipGeneratorInput): ShipArtifacts {
  const { projectName, ideaSummary, specSections, milestones, selectedIssues } =
    input;
  const taskTitles = selectedIssues.map((i) => i.title);
  const taskLines = taskTitles.length
    ? taskTitles.map((t, i) => `${i + 1}. ${t}`).join("\n")
    : "1. Deliver a minimal working happy-path prototype.";

  const shipBrief = [
    `# ${projectName} - Ship Brief`,
    "",
    "## Idea Summary",
    ideaSummary,
    "",
    "## Scope Snapshot",
    `- Spec sections: ${specSections.length}`,
    `- Milestones: ${milestones.length}`,
    `- Generated tasks selected for this run: ${taskTitles.length}`,
    "",
    "## Execution Plan",
    taskLines,
    "",
    "## Acceptance",
    "- The prototype should run locally with clear setup instructions.",
    "- The PR should describe what was automated and what remains manual.",
    "- Keep the implementation incremental and easy to review.",
    "",
    "_Generated by Sketch2Ship AI Agent (fallback mode)._",
    "",
  ].join("\n");

  const list =
    taskTitles.length > 0
      ? taskTitles
          .slice(0, 6)
          .map((t) => `<li>${t.replace(/</g, "&lt;")}</li>`)
          .join("")
      : "<li>Baseline scaffold created from the live spec.</li>";

  const prototypeHtml = [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="utf-8"/>',
    '  <meta name="viewport" content="width=device-width, initial-scale=1"/>',
    `  <title>${projectName} Prototype</title>`,
    '  <link rel="stylesheet" href="styles.css"/>',
    "</head>",
    "<body>",
    "  <main class=\"wrap\">",
    "    <section class=\"card\">",
    '      <span class="tag">Sketch2Ship Prototype</span>',
    `      <h1>${projectName}</h1>`,
    `      <p>${ideaSummary.replace(/</g, "&lt;")}</p>`,
    "      <h2>Auto-generated implementation focus</h2>",
    `      <ul>${list}</ul>`,
    "    </section>",
    "  </main>",
    '  <script src="app.js"></script>',
    "</body>",
    "</html>",
    "",
  ].join("\n");

  const stylesCss = [
    "body { font-family: ui-sans-serif, system-ui, -apple-system, sans-serif; margin: 0; background: #faf8f3; color: #2f2d2a; }",
    ".wrap { max-width: 900px; margin: 48px auto; padding: 0 20px; }",
    ".card { background: #fff; border: 1px solid #e5dfd3; border-radius: 12px; padding: 20px; }",
    "h1 { margin: 0 0 10px; font-size: 30px; }",
    "p { line-height: 1.6; }",
    "ul { margin: 10px 0 0; padding-left: 18px; line-height: 1.7; }",
    ".tag { display: inline-block; margin-bottom: 10px; padding: 4px 8px; border: 1px solid #ddd7ca; border-radius: 999px; font-size: 12px; background: #f6f2ea; }",
  ].join("\n");

  const readme = [
    "# Prototype",
    "",
    `This prototype was generated for **${projectName}**.`,
    "",
    "Open `index.html` in a browser to preview the generated MVP shell.",
    "",
  ].join("\n");

  return {
    shipBrief,
    files: [
      { path: "sketch2ship/prototype/index.html", content: prototypeHtml },
      { path: "sketch2ship/prototype/styles.css", content: stylesCss },
      { path: "sketch2ship/prototype/app.js", content: "// Auto-generated scaffold\n" },
      { path: "sketch2ship/prototype/README.md", content: readme },
    ],
  };
}

export async function generateShipArtifacts(
  input: ShipGeneratorInput
): Promise<ShipArtifacts> {
  const apiKey = process.env.GEMINI_API_KEY?.trim();
  if (!apiKey) {
    return buildFallbackShipArtifacts(input);
  }

  try {
    const contextJson = JSON.stringify(
      {
        projectName: input.projectName,
        ideaSummary: input.ideaSummary,
        specSections: input.specSections,
        milestones: input.milestones,
        selectedIssues: input.selectedIssues,
      },
      null,
      2
    );

    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model: "gemini-3.1-pro-preview",
      contents: `${SHIP_PROMPT}\n\n---\n\nProject context:\n${contextJson}`,
      config: {
        responseMimeType: "application/json",
      },
    });

    const text = response.text;
    if (!text) {
      return buildFallbackShipArtifacts(input);
    }

    const parsed = JSON.parse(text) as Partial<ShipArtifacts>;
    if (
      typeof parsed?.shipBrief !== "string" ||
      !Array.isArray(parsed?.files) ||
      parsed.files.length === 0
    ) {
      return buildFallbackShipArtifacts(input);
    }

    const validFiles = parsed.files.filter(
      (f): f is GeneratedFile =>
        typeof f === "object" &&
        f !== null &&
        typeof (f as GeneratedFile).path === "string" &&
        typeof (f as GeneratedFile).content === "string"
    );
    if (validFiles.length === 0) {
      return buildFallbackShipArtifacts(input);
    }

    return {
      shipBrief: parsed.shipBrief,
      files: validFiles,
    };
  } catch {
    return buildFallbackShipArtifacts(input);
  }
}
